name: InstaClone
options:
  bundleIdPrefix: com.demo
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
targets:
  InstaClone:
    type: application
    platform: iOS
    sources:
      - InstaClone
    info:
      path: InstaClone/Info.plist
    settings:
      base:
        GENERATE_INFOPLIST_FILE: "NO"
        SWIFT_VERSION: "5.9"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: ""
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGNING_ALLOWED: "NO"
